# Week 08: Local/Global Variables

## 0. Import Libraries 

In [23]:
# the "pandas" library is for manipualting datasets
import pandas as pd
import numpy as np
np.random.seed(100)

## 1. Array Continued (Stacking)

<font size='4'>

In [2]:
# 9.1.
x = np.ones((4,))
print(x)
print()
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Concatentate `my_array` and `x`
print(np.concatenate([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=1))

[1. 1. 1. 1.]

[1. 2. 3. 4. 1. 1. 1. 1.]

[[1. 2. 3. 4.]
 [1. 1. 1. 1.]]

[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]]


In [4]:
# 9.2. Stack arrays row-wise (by Python's default)


In [3]:
# 9.3.
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# if the second argument is an integer, it will split the array into an N equal sub-arrays
# Split `my_stacked_array` horizontally into two equal sub-arrays

# Split `my_stacked_array` vertically into two equal sub-arrays


In [4]:
# 9.4. Use indices in the form of a numpy array
print(np.split(my_stacked_array, np.array([2,5]), axis=1))
print("Or")
print(np.hsplit(my_stacked_array, np.array([2,5])))

NameError: name 'my_stacked_array' is not defined

In [8]:
# 9.5. Let's create a practical example and call back from the blood pressue problem.
# (2, 10, 5) refers to two sites, 10 patients each site, and 5 time points per patient.
BP_3d_arr = np.random.uniform(low=70, high=100, size=(2, 10, 5))
print(BP_3d_arr)
print(BP_3d_arr.shape)

[[[76.24621721 83.53775872 84.75528731 96.97228944 91.88081383]
  [93.10269319 81.26317743 80.31218606 89.65105618 91.3311398 ]
  [73.40612726 73.99086068 83.68117173 74.7920869  98.84925711]
  [95.12847235 85.60482061 76.54816773 74.04756168 99.37211036]
  [91.21130487 95.79926671 81.61517883 77.52502059 78.98314057]
  [95.70686585 84.18951972 89.89831141 94.17185822 77.58941514]
  [72.38720317 91.98281815 98.84192433 98.61414203 84.71497156]
  [88.96576193 91.9898506  97.0722851  74.86740756 82.17643967]
  [82.51272207 90.86773085 82.74541714 95.74342678 95.40797439]
  [72.10597342 79.0525724  99.38871043 71.0688099  84.77177941]]

 [[98.57130559 94.31721276 78.82991324 87.88700556 82.93533557]
  [87.77192509 96.81256314 86.62063569 84.78599522 79.57811372]
  [77.90097349 86.26841841 72.46793572 89.06910129 93.89215676]
  [98.64242516 90.53872815 84.648795   84.56242931 99.00078762]
  [76.34043662 82.34944415 99.6899673  70.8523557  91.03979542]
  [70.75514692 79.62645178 72.20581186

In [14]:
# 9.5.1 axis takes one number
BP_3d_arr_mean_1 = np.mean(BP_3d_arr, axis=0)
print(BP_3d_arr_mean_1)
print(BP_3d_arr_mean_1.shape)

BP_3d_arr_mean_2 = np.mean(BP_3d_arr, axis=1)
print(BP_3d_arr_mean_2)
print(BP_3d_arr_mean_2.shape)


BP_3d_arr_mean_3 = np.mean(BP_3d_arr, axis=2)
print(BP_3d_arr_mean_3)
print(BP_3d_arr_mean_3.shape)


BP_3d_arr_mean_3 = np.mean(BP_3d_arr, axis=-3)
print(BP_3d_arr_mean_3)
print(BP_3d_arr_mean_3.shape)

[[87.4087614  88.92748574 81.79260027 92.4296475  87.4080747 ]
 [90.43730914 89.03787028 83.46641088 87.2185257  85.45462676]
 [75.65355037 80.12963954 78.07455372 81.9305941  96.37070693]
 [96.88544875 88.07177438 80.59848137 79.30499549 99.18644899]
 [83.77587075 89.07435543 90.65257307 74.18868815 85.011468  ]
 [83.23100638 81.90798575 81.05206163 82.99919758 75.46580232]
 [73.73263521 90.40670327 90.99685858 96.77062748 80.95436862]
 [82.33367159 91.67342018 96.41056643 80.81954207 86.65452596]
 [85.33304157 88.82212467 89.27862143 96.66804378 95.44809708]
 [74.86998474 87.68961934 91.22130807 81.47682011 83.57550122]]
(10, 5)
[[84.07733413 85.82783759 87.48586401 84.74536593 88.50770418]
 [82.65492185 89.32035813 85.22294308 86.01597046 86.59821993]]
(2, 5)
[[86.6784733  87.13205053 80.94390074 86.14022655 85.02678232 88.31119407
  89.30821185 87.01434897 89.45545424 81.27756911]
 [88.50815454 87.11384657 83.91971713 91.47863305 84.05439984 73.5512274
  83.83626542 88.14234151 92.

In [18]:
# 9.5.2 axis takes two numbers
BP_3d_arr_mean_4 = np.mean(BP_3d_arr, axis=(1,2))
print(BP_3d_arr_mean_4)
print(BP_3d_arr_mean_4.shape)


BP_3d_arr_mean_5 = np.mean(BP_3d_arr, axis=(0,1))
print(BP_3d_arr_mean_5.shape)

TypeError: 'tuple' object is not callable

In [19]:
# 9.5.3. axis takes three numbers or None

BP_3d_arr_mean_7 = np.mean(BP_3d_arr, axis=(0,1,2))
print(BP_3d_arr_mean_7)
print(BP_3d_arr_mean_7.shape)

TypeError: 'tuple' object is not callable

## 2. Local and Global Variables

<font size="4"> 

Most of the variables we've defined so far are "global"

- Stored in working environment
- Can be referenced in other parts of the notebook



<font size = "5">
Example:

In [24]:
message_hello = "hello"
number3       = 3

In [25]:
print(message_hello + " world")
print(number3 * 2)

TypeError: 'tuple' object is not callable

<font size = "4">

Any "global" variable can be referenced inside functions

- However, this can lead to mistakes
- Preferrably, include **all** the inputs as parameters

<font size = "4">

$f(x,y,z) = x + y + z$

In [27]:
# 2.1. Correct Example:
def fn_add_recommended(x, y, z):
    return x+y+z

#recall passing arguments by name or by position
print(fn_add_recommended(x=1, y=2, z=5))
print(fn_add_recommended(x=1, y=2, z=10))

TypeError: 'tuple' object is not callable

In [10]:
# 2.2. Example that runs (but not recommended)
# Python will try to fill in any missing inputs
# with variables in the working environment


8
13


In [11]:
# 2.2.1.
del z # remove variables from a global scope


NameError: name 'z' is not defined

<font size ="4">

Variables defined inside functions are "local"

- Stored "temporarily" while running
- Includes: Parameters + Intermediate variables


### Local variables supercede global variables

In [ ]:
# 2.3.
def prin

In [28]:
# 2.4. An exception
depart_ls = ['bios', 'epid', 'bshes', 'eh', 'gh', 'hsrhp', 'nutrition']
for id_iter, depart_iter in enumerate(depart_ls):
    print(id_iter, depart_iter)

#they are still global variables, although we do not explicitly define them
print(id_iter, depart_iter)

TypeError: 'tuple' object is not callable

In [30]:
# 2.5. This is an example where we define a quadratic function
# (x,y) are both local variables of the function
# 
# When we call the function, only the arguments matter.
# any intermediate value inside the function are "invisible"
# or "inaccessible" when exiting the function.

def fn_square(x):
    y = x**2
    return y

x = 5
y = -5
print(fn_square(x=1.2))

print(x)
print(y)

TypeError: 'tuple' object is not callable

### Local variables are **not** stored in the working environment

In [32]:
# 2.6. The following code assigns a global variable x
x = 5
y = 4



# x and y values change inside the function only 
print(fn_square(x=10))

 #when exiting function, the values are still associated with global variables

print(x)
print(y)

print(fn_square(x=20))
print(x)
print(y)

TypeError: 'tuple' object is not callable

### To permanently modify a variable, use the "global" command

In [34]:
# 2.7.

# avoid using; may create confusion in code
def modify_x():
    global x
    x = x + 5

x = 1
print('x={} before modification'.format(x))
#now run the function will permanently increase x by 5
modify_x()
print('x={} after modify_x function'.format(x))

TypeError: 'tuple' object is not callable

### Try it yourself:

<font size = "4">
    
- What happens if we run `modify_x` twice?
- What happens if we add `global y` inside `fn_square`?

In [35]:
# 2.8. Write your own code here
def modify_x():
    global x
    x = x + 5

x = 1
print('x={} before modification'.format(x))
#now run the function will permanently increase x by 5
modify_x()
print('x={} after modify_x function'.format(x))

def modify_x():
    global x
    x = x + 10
    
x = 1
print('x={} before modification'.format(x))
#now run the function will permanently increase x by 10
modify_x()
print('x={} after modify_x function'.format(x))



TypeError: 'tuple' object is not callable

In [36]:
# 2.9.
def fn_square_2(x):
    global y
    y=x**2
    return y

#call the function
x = 5
y = -5

print('before running function')
print(x, y)
print('after running function')
print(fn_square_x(x=1.2))
print(x)
print(y)

TypeError: fn_square() got an unexpected keyword argument 'y'

### Built-in scope (Variables defined in Python)

<font size='4'>

- Functions such as `print()`, `len()`, `sum()`, `isinstance()` are all built-in functions in Python.
- They are available in any part of your code, so no need to define them.
- Python has a list of variables that are always available to prevent you from using the same names.
- Most of them are error names.

In [ ]:
# 2.10


### Enclosing scope (Variables defined in enclosing functions)

<font size='4'>
    
- They refer to variables defined in enclosing functions
- Enclosing functions are functions that contain other functions (nested or hierarachical functions)
- Enclosing scope is between local and global scopes in the LEGB rule

In [ ]:
# 2.11
# Define a function that contains another function


## 3. Work with Python scripts

<font size='4'>

Please open `week_08_main_1.py` and `week_08_main_2.py`.